name: 'deploy_cf'
on:
  push:
    branches: ["main"]

jobs:
  deploy_cf:
    runs-on: ubuntu-latest
    steps:
      use: actions/checkout@v4
      run: echo "Hacemos pull de codigo"
      run: echo "Correr migraciones"
      run: echo "Correr tests"
      run: echo "Correr linter"